### ISSUE TITLE
Marionette.js support?

### ISSUE THREAD

**Issue by stevewillard** [TrackJs/trackjs-package#1]
I'm trying out track.js (really cool by the way), but I'm running into a problem, and I think it's because I'm using Marionette. 

I'm trying the trackAll approach with Backbone found here:
https://gist.github.com/toddhgardner/7487037

Should I add more exclusions for the Marionette methods?

```
Uncaught Error: TrackJS Caught: TypeError   platform.min.js:7206
x.wrapErrorplatform.min.js:7221 
function.a.(anonymous function).b.contains.a.(anonymous function)backbone.marionette.map:2328 
e.CollectionView.e.View.extend.buildChildViewplatform.min.js:7221 
function.a.(anonymous function).b.contains.a.(anonymous function)backbone.marionette.map:2259 
e.CollectionView.e.View.extend.addChildplatform.min.js:7221 
function.a.(anonymous function).b.contains.a.(anonymous function)backbone.marionette.map:2152 
(anonymous function)lodash.underscore.min.js:7 
(anonymous function)lodash.underscore.min.js:15 
Dbackbone.js:966 
Collection.(anonymous function)platform.min.js:7221 
```

**Comment by stevewillard** [comment]
Got this working by excluding "childView"

Both Marionette's CollectionView and CompositeView use this property to reference an ItemView. It's a similar pattern to specifying a "model" in a collection, so I imagine it has the same sort of issues wrapping it.

Would be happy to add a PR to make a asterisk to Backbone for Marionette users if you can point me in the right direction.

Cool product!

Edit: also have to exclude "emptyView" -- it has the same issue.

**Comment by toddhgardner** [comment]
Awesome, thanks Steve! I've put together some guidance in our docs on this, and credited you! 
http://docs.trackjs.com/Examples/Integrating_with_Backbone
