### ISSUE TITLE
trackJs is not defined

### ISSUE THREAD

**Issue by AlexBeauchemin** [TrackJs/trackjs-package#12]
As per the doc 
http://docs.trackjs.com/tracker/quickStart
https://my.trackjs.com/install

Using `trackJs.track("...");` in the browser console doesn't work anymore and is returning `Uncaught ReferenceError: trackJs is not defined(…)`

Using the cdn in case that matters

**Comment by BrandesEric** [comment]
Hi Alex, are you running uBlock or AdBlock+ by chance?

**Comment by AlexBeauchemin** [comment]
Hi, I have uBlock but it's disabled for this specific domain
Trackjs is succesfully loaded according to the network tab

**Comment by BrandesEric** [comment]
Is there a public URL I can peek at?  Using `trackJs.track()` should absolutely still work.  Are you seeing the file come down from the CDN?

**Comment by AlexBeauchemin** [comment]
Yes everything is loaded, what is weird right now is that I have 1 of my 3 website that is working and the other 2 doesn't work. But they are only cnames, all pointing to the same ip. Could this be a problem from your cdn distributing a bugged file sporadically?

**Comment by AlexBeauchemin** [comment]
Tried on many computers, sometimes it works, sometimes it doesn't. We have to refresh till it starts working after clearing cache/ incognito mode

**Comment by AlexBeauchemin** [comment]
I think I have some steps to reproduce:
- Open chrome in ingonito (keep console closed)
- Load site
- Open chrome's console
- try `trackJs.track('...')`

Seems like it works fine as long as the chrome console is open before loading the site. 
Doesn't work if the console is opened after the load

Chrome 52.0.2743.116 on osx

**Comment by BrandesEric** [comment]
Does this only happen in Chrome?  I am wondering if there's something going on with Chrome specifically that's causing the issue.  That is, are users of your site actually experiencing problems, or is it just a console/debug tool issue?

**Comment by AlexBeauchemin** [comment]
Same in firefox, but it doesn't output any error (no `Uncaught ReferenceError: trackJs is not defined(…)`, it fails silently

Seems like only a console/debug tool issue. We are still receiving errors in our dashboard. I guess (hope) this doesn't impact error logging

**Comment by BrandesEric** [comment]
Hi Alex, I've been trying to reproduce, but cannot reproduce in Firefox or Safari.   I did try setting trackJs = null, and then tracking an error to see if it fails silently for me.  It does not, so perhaps something else is going on?  One thing you might try, if you're concerned about it, is bundling the script.  We don't see any issues with the CDN currently but if there are network gremlins (read: hostile proxies) between you and the CDN, bundling may help :)

**Comment by AlexBeauchemin** [comment]
Yeah I might try to target the problem more precisely, I'll try at home on a windows machine to see if I can reproduce

**Comment by BrandesEric** [comment]
@AlexBeauchemin I was able to reproduce the issue.  It's a Chrome dev tools problem I believe.  Here is a screenshot of the issue.  Please note the file.  It's current frame context is within a Chrome extension (possibly uBlock) 
![image](https://cloud.githubusercontent.com/assets/640877/17793690/d9db61d2-656e-11e6-97a7-cababc00e2ee.png)

Here is what it SHOULD look like.  Note the "Top" for the frame context.
![image](https://cloud.githubusercontent.com/assets/640877/17793711/0063dcf8-656f-11e6-958e-f00d4d5d523c.png)

These two screenshots were taken on the same browser session.  For some reason Chrome will occasionally run the console from the wrong context.  It does appear to be somewhat of a race condition.  I suspect it's uBlock or LastPass (which are the two extensions I use primarily)

If you try and reproduce again, please let me know if you're seeing the same thing.

**Comment by AlexBeauchemin** [comment]
You're right, the only extensions I have running in incognito are uBlock and Tampermonkey , so I assume uBlock is wrongly taking context when the console is closed at page load.

Pretty sure there's not much that can be done right now, and it's not a big deal now that we know how to avoid it. Will probably happen to a lot of people though
Thanks for the help and quick response.

**Comment by BrandesEric** [comment]
Yep!  We'll probably look in to adding a section to our troubleshooting section in the docs.
