### ISSUE TITLE
License clarity

### ISSUE THREAD

**Issue by stevecrozz** [TrackJs/trackjs-package#16]
The license file in trackjs-package doesn't appear to reference the code in the package itself, but instead appears to be a copy of the terms of service for trackjs.com. Can you please clarify what license covers the code in this package?

**Comment by BrandesEric** [comment]
If you check this section out: 
https://github.com/TrackJs/trackjs-package/blob/master/LICENSE.md#grant-of-license-and-restrictions-on-use 

You'll see references to "The Error Tracking Agent" which is how we refer to the tracker script itself (the code in this repository).  So the license granted to the tracker script is the same license as applies to the code here.

Does that help?  If not, let me know!

**Comment by stevecrozz** [comment]
Yes I think it does. It wasn't clear to me that tracker.js was an 'agent' in this language. I suppose this means tracker.js doesn't fall under any definition of open source. Github seems like an odd (and perhaps misleading) choice to distribute proprietary, closed-source software. Oh well. Thanks for the pointer.
