### ISSUE TITLE
Potential CORS issue?

### ISSUE THREAD

**Issue by xcskier56** [TrackJs/trackjs-package#17]
I recently started using the ember-cli trackjs addon and started getting this error. The addon added `crossorigin="anonymous"` to the script tag. I'm not sure if this is actually an issue, but since it prevented the script from loading I though I'd bring it to your attention.

    Access to Script at 'https://d2zah9y47r7bi2.cloudfront.net/releases/current/tracker.js' 
    from origin 'http://localhost:5000' has been blocked by CORS policy: 
    No 'Access-Control-Allow-Origin' header is present on the 
    requested resource. Origin 'http://localhost:5000' is therefore not allowed access.

**Comment by toddhgardner** [comment]
Hey @xcskier56, thanks for reaching out with this. It does appear the CORS headers are missing from this URL.

Some time ago, we migrated our scripts to `https://cdn.trackjs.com/releases/current/tracker.js`, which appears to be working correctly. I'd recommend switching to this one, as it will resolve your immediate issue.

Also, you should note that we encountered a lot of issues with [Corporate Proxies](https://trackjs.com/blog/crossorigin-scripts-and-corporate-proxies/) while doing the crossorigin tagging on the script, which eventually led us to stop recommending it.

**Comment by toddhgardner** [comment]
Hey @xcskier56, it appears the CORS headers are working correctly. Note that they are only added if the request is made from a <script> tag; asking for the file directly will not have the headers.

I just verified this: 
`<script src="https://d2zah9y47r7bi2.cloudfront.net/releases/current/tracker.js" crossorigin="anonymous"></script>`
and it works correctly for me.

Can you please verify that there is not a local proxy blocking or rewriting your requests?

**Comment by xcskier56** [comment]
I noticed this on my home network, and seeing as I configured it, I highly doubt there is, but i'm no network guru so theres always a chance. I looked at my settings and I don't see anything that would make me think that this is the problem.

This error is not consistently occurring. I've noticed it in localhost, staging and production. I think it occurs about 25% of the time. I've only seen it on first page load.

**Comment by xcskier56** [comment]
If it's of any help, I noticed it again on our production app. Unfortunately, i opened the dev tools after loading the page, so I can't inspect the network requests.

I'm removing the `crossOrigin=anonymous` for now to prevent these errors.

**Comment by BrandesEric** [comment]
@xcskier56 I think I recall seeing something like this before. It was related to caching of CORS requests.  I wonder if it has anything to do with: https://bugs.chromium.org/p/chromium/issues/detail?id=409090

From the Bug:

> Basically: 
>1. Fetch a cross origin image without the crossorigin='anonymous' attribute or via CSS to start a regular >fetch without CORS headers
>2. Wait for the image to be downloaded and cached.
>3. Start the same request but with crossorigin='anonymous'
>4. Chrome will fetch from cache, but the CORS headers won't be cached due to the first regular request.
>5. This will result in a CORS error on the second fetch. 

I suspect what happened was that the script was originally loaded via <script src=""></script> and was cached without the CORS headers (since there was no `crossorigin` attribute).

Now that you're adding the 'crossorigin' attribute it's failing.  If you disable your browser cache do you see the issue?  If not, and you clear your cache, and *only* ever load it via `crossorigin=anonymous` do you get better results?
