### ISSUE TITLE
Support for Browserify

### ISSUE THREAD

**Issue by slorber** [TrackJs/trackjs-package#2]
Please export the TrackJS npm published module so that we can require it.

The following code should be supported:

``` javascript
var TrackJs = require("trackjs");

TrackJs.configure({
        token: "token"
});

TrackJs.track("test")
```

Unfortunately TrackJS module on NPM seems to not export its content and use a `trackJs` global variable, and also seems to require the token to be configured before lib loading, making call to configure with a token useless according to this warning
`TrackJS could not find a token`

**Comment by marcbachmann** [comment]
:+1:

**Comment by toddhgardner** [comment]
Will investigate what this will take.

**Comment by karellm** [comment]
:+1: It took me a while to figure it out. 

The documentation states we can use `_trackJs` or `trackJs.configure()` but it is not the case. So we need to rely on hack to inject `_trackJs` prior the script loads which is far from ideal!

**Comment by don-smith** [comment]
:+1: A common practice is to NOT check things like tokens into source control. We use a local config service (Angular) to bring in these tokens. I'm still trying to figure out how to do this for TrackJS. Far from ideal indeed!

**Comment by toddhgardner** [comment]
This is on our backlog and we're prioritizing it with other work. I'll update here when we have a timetable.

**Comment by jherdman** [comment]
To add to this ticket, it'd be great if the bower package [exported an AMD module](https://github.com/substack/browserify-handbook#standalone). This would make [an entire part](https://github.com/jherdman/ember-cli-trackjs/blob/d39d8ad37b7358b3871b2a5b986eec93734d3002/addon/services/trackjs.js) of my ember-cli-trackjs package obsolete.

**Comment by toddhgardner** [comment]
This has been added in agent v3.0.0, currently in canary testing. You can reference it as a module from npm:

`npm install trackjs@canary`

```javascript
import { TrackJS } from 'trackjs';
TrackJS.install({ token: 'YOUR_TOKEN' });
```
