### ISSUE TITLE
license

### ISSUE THREAD

**Issue by crooy** [TrackJs/trackjs-package#20]
Hi,

your library has no license and my company needs one for each lib we use.... could you add one?

**Comment by toddhgardner** [comment]
Hi @crooy, There is a [license](https://github.com/TrackJs/trackjs-package/blob/master/LICENSE.md) in the package describing the terms of service to user our tracking library and service. What would you like to see different?

**Comment by crooy** [comment]
Well if you put it in package.json, then the tool we use to generate a list of all licenses used in our stack will find it :-)

**Comment by toddhgardner** [comment]
According to [this documentation from npm](https://docs.npmjs.com/files/package.json), we should use `{ "license" : "SEE LICENSE IN LICENSE.md" }`. Will that be acceptable for you?

**Comment by crooy** [comment]
i think my "are-we-in-any-licence-trouble"-script will be able to find and
flag that :-)

Thanks! i only have on licence-less less/css thing to fix left now!

Thanks again!

**Comment by toddhgardner** [comment]
@crooy fixed in 2.7.1
