### ISSUE TITLE
Add dedupe to tracker.d.ts

### ISSUE THREAD

**Issue by aaronjensen** [TrackJs/trackjs-package#21]
`dedupe` looks handy and it's [in the docs](http://docs.trackjs.com/tracker/configuration). If it's real, could it be added to tracker.d.ts please? Also, what is its default?

**Comment by toddhgardner** [comment]
Hey @aaronjensen, I'll get right on that! In the mean time, the value is boolean, default is `true`.

**Comment by aaronjensen** [comment]
Interesting, then I'm not sure it's working :) what version did it land in? I just upgraded, so I'll see if it's working now.

**Comment by toddhgardner** [comment]
@aaronjensen Looks like it [hit in 2.7.0](https://github.com/TrackJs/trackjs-package/blob/master/CHANGELOG.md). Pushing out the change with the typing change shortly.
