### ISSUE TITLE
Hard to debug error: `undefined undefined: undefined undefined`

### ISSUE THREAD

**Issue by torjusb** [TrackJs/trackjs-package#22]
A little while ago we updated the tracker.js library to a version which added support for `fetch` (2.8.0). After doing that, we started seeing a lot of errors with the message `undefined undefined: undefined undefined`, marked as an "Ajax error".

After digging through the minified code a bit, I found the following lines within the `fetch`-patch code:

```js
return h.then(function(d) {
    var e = a.get("n", h._tjsId);
    e && (f.defaults(e, {
        completedOn: f.isoNow(),
        statusCode: d.status,
        statusText: d.statusText
    }), b.error && 400 <= d.status && c("ajax", e.statusCode + " " + e.statusText + ": " + e.method +
        " " + e.url));
    return d
})
```

This seems to be the culprit of the issue. I'm unsure if this is a bug in the tracker library or a bug on our side. I'm guessing maybe it is caused by an empty server `Response` or similar.

Note that we are currently on the latest version of the tracker (2.8.4), but we still see the issue.

**Comment by toddhgardner** [comment]
Hey @torjusb, So sorry for the trouble. Yes, this was a bug in 2.8.0 that we fixed in 2.8.3. We are currently at 2.8.4. Would it be possible for you to upgrade and see if you are still seeing this?
