### ISSUE TITLE
Feature request: Trello integration

### ISSUE THREAD

**Issue by jasonbarry** [TrackJs/trackjs-package#24]
It would be nice if errors that occurred above a frequency threshold made a Trello card in a board of your choosing. Rollbar has this feature and it's quite helpful.

**Comment by toddhgardner** [comment]
Hey @jasonbarry. Thanks for the suggestion, that's good feedback. 

You can do this today, indirectly, using the email integration. [Add the email address of your board as a Notification channel](https://my.trackjs.com/Account/Notifications) and send your Error Rate alerts to it. 

Will that work for you?

**Comment by jasonbarry** [comment]
@toddhgardner yes! That's awesome, I didn't know that was possible. Feel free to close this issue if you'd like, or leave it open to track direct integration.
