### ISSUE TITLE
"Not a product" error for some users from track.js package (latest)

### ISSUE THREAD

**Issue by rsolomon** [TrackJs/trackjs-package#25]
We're getting a the following error from a few logged out Chrome users:

```
Message:
Not a Product
```

It's pointing to the following places in the tracker script:

```
{anonymous} @ https://cdn.trackjs.com/releases/current/tracker.js 45:47 Why is This Here? 
E @ https://cdn.trackjs.com/releases/current/tracker.js 5:415
```

**Comment by toddhgardner** [comment]
Hey @rsolomon, thanks for bringing this up. This is actually *not* a tracker bug, it's an unhandled promise rejection from some injected code, probably a browser extension.

We're still trying to track down which one, but I suspect the Honey couponing extension. I'll let you know when we lock it down.

**Comment by rsolomon** [comment]
Thanks @toddhgardner . Is there by chance a similar issue with "Failed to fetch" errors? I know that's the result of an uncaught 40x error from a Promise, but I'm only seeing it happen with a single user. It's consistent across pages, and is not reproducible even in a similar environment (OS and browser version).

**Comment by toddhgardner** [comment]
Hey @rsolomon. Could be, but I don't have conclusive evidence yet. We have "Failed to fetch" in our account as well, but I think it might be a consequence of network failures on particular browsers. Every case I've seen so far has a failed `fetch` request in the timing, but I'm not sure how to get more information from it yet. 

I will look more into it!

**Comment by BobDankert** [comment]
I've seen the "Not a Product" error as well and noticed it on here. Is it typical/common for browser extension errors to make it into TrackJS? Is there any way to tell or differentiate if errors are being thrown by extensions, rather than by the site code?

**Comment by toddhgardner** [comment]
Hi @BobDankert. Anything that operates on your document will get detected and reported by the TrackJS agent. If a browser extension reaches into your page and causes an error, as is in the case of Honey and "Not a Product", we will capture that too.

We are adding a Solution to the TrackJS UI to show more information about this error and that it is safe to Ignore it.

I have also reached out to Honey with details about this to see if they can repair their extension.

I will also be filing a bug with Chromium in the near future as we believe the stack trace of the extension code should be visible to us. Currently, the browser security policy filters it out as it is considered a separate origin.
