### ISSUE TITLE
Enable TrackJS on Web Worker

### ISSUE THREAD

**Issue by cooperd** [TrackJs/trackjs-package#26]
As part of my application i need to use web worker(s). 
I looked into the documentation and it seems that i must have the `window` object in order to configure TrackJS.

Please provide support for using and monitoring js errors on web workers.

**Comment by toddhgardner** [comment]
Hey @cooperd, thanks for the suggestion. Yea, this is a good idea and we've been looking at how best to do it. Can you elaborate on what kinds of failure modes you'd like to see monitored in your web worker process?

**Comment by liorur** [comment]
Id say the minimal requirement you be allow me to monitor unhandled
-exceptions
-promises
-postMessage
-onmessage

it would also be very useful if i could set context on the worker errors

thanks

**Comment by dicarlo2** [comment]
@toddhgardner any updates on implementing this?

**Comment by toddhgardner** [comment]
@dicarlo2 Yes, thanks for asking. we did an internal prototype of it and found we needed to update the agent to support modular loading before this would be effective. We're finishing that up now and will be released as 3.0.0. We will return to this once that has launched.

**Comment by nullrocket** [comment]
Any news on this?

**Comment by toddhgardner** [comment]
@nullrocket I'm afraid not :( This fell off our priorities unfortunately. 
If you can give me some information about your use case, I can probably bump it back up.
What do you want to capture from the worker thread?

**Comment by nullrocket** [comment]
@toddhgardner almost all of our applications logic lives in webworkers, it would be nice to have at least https://github.com/TrackJs/trackjs-package/issues/26#issuecomment-357666828

**Comment by lstrojny** [comment]
Any news on this?

**Comment by toddhgardner** [comment]
Hey @lstrojny, Yes there is! We have this working in our development environment now, but we need to do some compatibility testing and such. It should be part of our next release, maybe as soon as next week.

**Comment by toddhgardner** [comment]
This is on track to be released this week. We have an build infrastructure Node upgrade that we need to deploy and test, then this will go out right afterwards as 3.8.0. I will update here when it is done.

**Comment by toddhgardner** [comment]
This has been released to canary as 3.8.0. you can access it via `npm install trackjs@canary` or at [https://cdn.trackjs.com/agent/v3/canary/t.js](https://cdn.trackjs.com/agent/v3/canary/t.js).

**Comment by toddhgardner** [comment]
Released.
