### ISSUE TITLE
Using TrackJs in a callback

### ISSUE THREAD

**Issue by Shomari** [TrackJs/trackjs-package#29]
I am making a front-end api call to a third party service and want to use trackJs to log some data from the response.   However, anytime I put trackJs.track(data_i_want) in the callback, then it doesn't actually track anything.  Everything works as expected if I make the .track call pretty much anywhere else in the app except in the callback function

**Comment by toddhgardner** [comment]
Hey @Shomari, thanks for reaching out. When you call `trackJs.track()`, we attempt to make the value you pass into an `Error` object so that we can see a stack trace. If the data you send is unserializable, it could prevent an error from sending, or send a different error than what you expect.

Can you share some example code of what you are seeing? Can you share what `data_i_want` is at the time you invoke track?

**Comment by Shomari** [comment]
@toddhgardner even if I just put in a simple string then nothing happens.   This issue only happens in the callback method and not anywhere else.    In the example code, the first trackJs.track will fire,  but the second one that is in the callback messageListener (with the string 'in callback') won't fire

``` 
  signAgreement(){
    var that = this;
    trackJs.track('first')
    HelloSign.init(client_id);
    HelloSign.open({
      url: sign_url,
      allowCancel: true,
      messageListener(eventData) {

        trackJs.track('in callback')
        var eventMessage = eventData.event;
        var signatureId = eventData.signature_id;
          that.props.onHide();
          NotificationActions.success('Document successfully signed');
        }
      },
    });
  },```

**Comment by toddhgardner** [comment]
@Shomari I'm not aware of any situation in our script that would know the difference, or care at all between these two calls. Are you confident that the callback is firing? If you attach a debugger, or print a console message, do you see it firing?

**Comment by Shomari** [comment]
yup, I've put debugger in and have console logged the data with success.  Also our notificationAction also fires.  Its just that we don't get any data showing up on my.trackjs.com for our account

**Comment by toddhgardner** [comment]
@Shomari can you email us your account name or email address so we can dig in further? `hello@trackjs.com`.

Have you created a clientside filter using the [onError callback](https://docs.trackjs.com/tracker/tips#ignoring-errors)?

**Comment by Shomari** [comment]
Just so you all aren't spinning your wheels we think its because browserfiy or something else thats preventing trackJs from firing (we keep getting entity too large errors) so we doubt it has anything to do with the trackJs code

**Comment by toddhgardner** [comment]
@Shomari thanks for the update!! You may receive an Entity too large from us when sending an error if the text is more than 100kb. We do this to protect our system against high volume and attack.

If you have lots of very large objects getting logged to the console, it is possible you hit this limit.

**Comment by Shomari** [comment]
yeah we aren't directly sending large objects but think something else maybe hijacking the call and adding stuff to it.  Thanks for your responsiveness
