### ISSUE TITLE
TrackJS breaks isomorphic applications

### ISSUE THREAD

**Issue by dicarlo2** [TrackJs/trackjs-package#30]
The latest 3.0 update breaks applications that are intended to run in both the browser and node - it's impossible to `import` the package without it doing something with the `window`.

**Comment by toddhgardner** [comment]
Good find @dicarlo2, thank you. The agent doesn't support NodeJS today, but I can understand why you would include it for isomorphism. Would you be satisfied if the script simply no-oped, and perhaps printed a warning message to the console, when imported from Node?

**Comment by toddhgardner** [comment]
@dicarlo2 hey, just following up. Can you tell us more about your use case?

**Comment by dicarlo2** [comment]
@toddhgardner sorry for the delay. Yes if it simply no-oped that would be great. FWIW, that's exactly what we do now as a workaround: https://github.com/neo-one-suite/neo-one/blob/master/packages/neo-one-react-common/src/TrackJS.ts.

I'd rather not have a warning message personally, but I can see it being useful for people that might not realize that TrackJS can't be used from NodeJS. With that said, is there any particular reason TrackJS is not usable from NodeJS? Would be great to track server-side errors with the same framework we use for client-side errors.

**Comment by toddhgardner** [comment]
@dicarlo2 Awesome, we'll get something put together soon. 

Node support is something we've talked about for a long time. I don't think there are any issues making the agent compatible with it, it's more a challenge with how we organize and report on the data compared to the client-side errors. Noise is less of an issue on the server side, most errors captured would be relevant, so how do we reflect the additional importance there.

**Comment by erikdubbelboer** [comment]
Is there any update on this? Do all server side React users have to keep using the workaround from @dicarlo2 ?

**Comment by toddhgardner** [comment]
@erikdubbelboer no update yet I'm afraid. Thanks for pinging this though. Let me look at what it will take to get it to no-op for node.

**Comment by toddhgardner** [comment]
This has been fixed in 3.1.0, which has gone to Canary testing today. Will be generally available this week.
