### ISSUE TITLE
trackjs CDN returns access denied for v3.0

### ISSUE THREAD

**Issue by jusurb** [TrackJs/trackjs-package#31]
GET https://cdn.trackjs.com/releases/3.0.0/tracker.js
returns Access Denied now, it used to work with all 2.x versions

we want to fetch a specific version of trackjs not always latest because we use integrity hashes

**Comment by BrandesEric** [comment]
@Gamesh Sorry for the trouble - we ended up slightly changing the URL for v3.  The old script was called `tracker.js`, which was getting flagged by aggressive ad blockers in some cases.  The new file is shortened to simply `t.js`.  We also re-arranged the pathing structure a bit.

You can find it here:
https://cdn.trackjs.com/agent/3.0.0/t.js

Our changelog will always be updated with the correct URL for each version:
https://github.com/TrackJs/trackjs-package/blob/master/CHANGELOG.md

Thanks!

**Comment by jusurb** [comment]
thanks that info was missing from the docs, would be good to add it there too.

does using "latest" mean latest stable version? or newest version (might be also beta/alpha)?

**Comment by BrandesEric** [comment]
The docs are still being updated, but they're next on our list of things to fix up!

`latest` is the current stable version. We have a `canary` tag in NPM (or you can hit the canary url on the CDN: https://cdn.trackjs.com/agent/v3/canary/t.js) if you want to use the beta version for any reason.

**Comment by jusurb** [comment]
thanks
