### ISSUE TITLE
New typescript types do not work with TrackJS on window

### ISSUE THREAD

**Issue by aaronjensen** [TrackJs/trackjs-package#33]
The new types export a namespace, but should export a declared instance of an interface and expose it globally as well. 

Something like this:

```ts
// Type definitions for TrackJS 3.0.0
// Project: https://github.com/TrackJS/trackjs-package

export interface TrackJSObject {
  /**
   * Adds a new key-value pair to the metadata store. If the key already exists
   * it will be updated.
   *
   * @param {String} key
   * @param {String} value
   */
  addMetadata(key: string, value: string): void

  /**
   * Invokes the provided function within a try/catch wrapper that forwards
   * the error to TrackJS.
   *
   * @param {Function} func The function to be invoked.
   * @param {Object} context The context to invoke the function with.
   * @param {...} Additional arguments passed to the function.
   * @return {*} Output of the function.
   */
  attempt(func: Function, context?: any, ...args: any[]): any

  /**
   * Configures the instance of TrackJS with the provided configuration.
   *
   * @param {Object} options The Configuration object to apply
   * @returns {Boolean} True if the configuration was successful.
   */
  configure(options: TrackJSConfigureOptions): boolean

  /**
   * Non-exposed browser console logging. Use this private console to prevent
   * messages from being exposed into the standard browser console.
   */
  console: {
    /**
     * Records context into the Telemetry log with normal severity
     *
     * @param {...} args Arguments to be serialized into the Telemetry log.
     */
    log(...args: any[]): void

    /**
     * Records context into the Telemetry log with DEBUG severity
     *
     * @param {...} args Arguments to be serialized into the Telemetry log.
     */
    debug(...args: any[]): void

    /**
     * Records context into the Telemetry log with INFO severity
     *
     * @param {...} args Arguments to be serialized into the Telemetry log.
     */
    info(...args: any[]): void

    /**
     * Records context into the Telemetry log with WARN severity
     *
     * @param {...} args Arguments to be serialized into the Telemetry log.
     */
    warn(...args: any[]): void

    /**
     * Records context into the Telemetry log with ERROR severity. If console
     * errors are enabled, which is default, this will also transmit an error.
     *
     * @param {...} args Arguments to be serialized into the Telemetry log.
     */
    error(...args: any[]): void
  }

  /**
   * Running version of the tracker script
   */
  hash: string

  /**
   * Installs the agent into the current browser document.
   *
   * @param options The configuration object to apply.
   */
  install(options: TrackJSInstallOptions): boolean

  /**
   * Removes a key from the metadata store, if it exists.
   *
   * @param {String} key
   */
  removeMetadata(key: string): void

  /**
   * Directly invokes an error to be sent to TrackJS.
   *
   * @param {Error|Object|String} error The error to be tracked. If error does
   *        not have a stacktrace, will attempt to generate one.
   */
  track(error: Error | Object | String): void

  /**
   * Running version of the tracker script
   */
  version: string

  /**
   * Returns a wrapped and watched version of the function to automatically
   * catch any errors that may arise.
   *
   * @param {Function} func The function to be watched.
   * @param {Object} context The context to invoke the function with.
   * @return {Function} Wrapped function
   */
  watch(func: Function, context?: any): Function

  /**
   * Wrap and watch all of the functions on an object that will
   * automatically catch any errors that may arise.
   *
   * @param {Object} obj The Object containing functions to be watched
   * @return {Object} Object now containing wrapped functions.
   */
  watchAll(obj: Object): Object
}

/**
 * String formatted as an ISO-8601 Date. Example 0000-00-00T00:00:00.000Z
 */
export interface ISO8601DateString extends String {}

/**
 * Payload of an error sent to TrackJS. Useful when manipulating errors via
 * the `onError` callback.
 */
export interface TrackJSErrorPayload {
  /** Stack trace at time of asynchronous callback binding. */
  bindStack?: string
  /** Timestamp of the asynchronous callback binding. */
  bindTime?: ISO8601DateString
  /** Browser Console Telemetry */
  console: {
    /** Timestamp the event occurred */
    timestamp: ISO8601DateString
    /** Console severity of the event */
    severity: string
    /** Formatted message captured */
    message: string
  }[]
  /** Context provided about the customer session */
  customer: {
    /** Customer application id */
    application?: string
    /** Unique Id describing the current page view */
    correlationId: string
    /** Customer-provided visitor session ID */
    sessionId?: string
    /** Customer token */
    token: string
    /** Customer-provided visitor user ID */
    userId?: string
    /** Customer-provided system version ID */
    version?: string
  }
  /** How the error was captured. */
  entry: string
  /** Context about the browser environment */
  environment: {
    /** How long the visitor has been on the page in MS */
    age: number
    /** Other discovered JavaScript libraries on the DOM. */
    dependencies: {[name: string]: string}
    /** browser userAgent string */
    userAgent: string
    /** current window height */
    viewportHeight: number
    /** current window width */
    viewportWidth: number
  }
  /** Custom environment metadata. */
  metadata: {
    /** metadata group name */
    key: string
    /** metadata value */
    value: string
  }[]
  /** Error message */
  message: string
  /** Navigation Telemetry */
  nav: {
    /** Timestamp of the navigation event */
    on: ISO8601DateString
    /** Navigation method used. IE "replaceState" "setState" */
    type: string
    /** Previous URL */
    from: string
    /** New URL */
    to: string
  }[]
  /** Network Telemetry */
  network: {
    /** Timestamp the request started */
    startedOn: ISO8601DateString
    /** Timestamp the request completed */
    completedOn: ISO8601DateString
    /** HTTP Method used */
    method: string
    /** URL Requested */
    url: string
    /** HTTP Status Code */
    statusCode: number
    /** HTTP Status Text */
    statusText: string
    /** Mechanism of network use. IE "fetch", "xhr" */
    type: string
  }[]
  /** location of the browser at the time of the error */
  url: string
  /** stack trace */
  stack: string
  /** client-reported time the error occurred */
  timestamp: ISO8601DateString
  /** Visitor Action Telemetry */
  visitor: {
    /** timestamp the event occurred */
    timestamp: ISO8601DateString
    /** visitor action taken. "input" or "click" */
    action: string
    /** DOM element acted upon */
    element: {
      /** name of the element tag. IE "input" */
      tag: string
      /** hashmap of element attributes */
      attributes: {[attributeName: string]: string}
      /** value of the element */
      value: {
        /** Number of characters in the value */
        length: number
        /** Patterns describing the value. */
        pattern: string
      }
    }
  }[]
  /** version of the tracker.js lib */
  version: string
  /** Number of messages throttled clientside */
  throttled: number
}

/**
 * Configuration options that can be passed to `trackJs.configure()`
 */
export interface TrackJSConfigureOptions {
  /**
   * Whether duplicate errors should be suppressed before sending.
   * @default true
   */
  dedupe?: boolean

  /**
   * Whether to attempt discovery of other JavaScript libs on the page.
   * @default true
   */
  dependencies?: boolean

  /**
   * Custom handler to be notified *before* an error is transmitted. Can be used
   * to modify or ignore error data.
   */
  onError?: (payload: TrackJSErrorPayload) => boolean

  /**
   * Custom handler for serializing non-string data in errors and telemetry
   * events.
   */
  serialize?: (what: any) => string

  /**
   * Id of the visitor session. Use this to correlate TrackJS
   * Error reports with other reporting data.
   */
  sessionId?: string

  /**
   * Id of the visitor. Use this to identify the current user for support.
   */
  userId?: string

  /**
   * Id of the running application. Recommend to use either a SEMVER
   * representation, or a VCS Hash Key.
   */
  version?: string
}

/**
 * Configuration options that are initialized from `window._trackJs`
 */
export interface TrackJSInstallOptions extends TrackJSConfigureOptions {
  /**
   * TrackJS Application token. Get this from `https://my.trackjs.com/Account/Applications`
   */
  application?: string

  callback?: {
    /**
     * Whether errors should be recorded when caught from callback functions.
     * @default true
     */
    enabled?: boolean
    /**
     * Whether stack traces should be generated at the time of invocation of an
     * asynchronous action. This will produce stack traces similar to the
     * "async" traces in Chrome Developer tools.
     * There is a performance impact to enabling this. Confirm behavior in your
     * application before releasing.
     * default false.
     */
    bindStack?: boolean
  }

  console?: {
    /**
     * Whether events should be recorded from the console.
     * @default true
     */
    enabled?: boolean
    /**
     * Whether console messages should be passed through to the browser console
     * or hidden by TrackJS. Useful for removing debug messaging from production.
     * @default true
     */
    display?: boolean
    /**
     * Whether an error should be recorded by a call to `console.error`.
     * @default true
     */
    error?: boolean
    /**
     * Limit the console functions to be watched by whitelisting them here.
     * @default ["log","debug","info","warn","error"]
     */
    watch?: string[]
  }

  /**
   * Whether the tracker script is enabled.
   * @default true
   */
  enabled?: boolean

  network?: {
    /**
     * Whether events should be recorded from the network.
     * @default true
     */
    enabled?: boolean
    /**
     * Whether an error should be recorded by XHR responses with status code
     * 400 or greater.
     * @default true
     */
    error?: boolean
  }

  /**
   * Your account token. Get this from `https://my.trackjs.com/install`
   */
  token: string

  visitor?: {
    /**
     * Whether events should be recorded from the visitor actions.
     * @default true
     */
    enabled?: boolean
  }

  window?: {
    /**
     * Whether events should be recorded from globally unhandled errors.
     * @default true
     */
    enabled?: boolean
    /**
     * Whether events should be recorded from globally unhandled promise
     * rejections, if supported.
     * @default true
     */
    promise?: boolean
  }
}

declare var TrackJS: TrackJSObject

declare global {
  var TrackJS: TrackJSObject | undefined
}

export {TrackJS}
```

**Comment by toddhgardner** [comment]
Hey @aaronjensen! Thanks so much for the report and the example. I'm checking on this right now.

**Comment by toddhgardner** [comment]
@aaronjensen your example seems to work great, but I'd like to make it a bit more explicit that `TrackJS` hangs off of window, and not simply a global. If I modify your example like this:

```typescript
declare global {
  var TrackJS: TrackJSStatic | undefined;
  interface Window {
    TrackJS: TrackJSStatic | undefined;
  }
}

declare var TrackJS: TrackJSStatic
export { TrackJS }
```

Then the definitions specify that we can either use it globally like `TrackJS`, or accessible off of `window.TrackJS`. I think this should make it easier to use, especially with your other issue #34  where we should check if `window.TrackJS` is truthy before referencing it.

**Comment by aaronjensen** [comment]
Works for me. By the way, I'd probably recommend `export default TrackJS` so it plays well with webpack externals.

**Comment by toddhgardner** [comment]
@aaronjensen we don't do a default export from the module definition either. I thought the default module problems were fixed in webpack.

**Comment by aaronjensen** [comment]
Yeah, I meant from the module as well. Oh, does externals trackjs: 'TrackJS' work with a named export? I didn't think it did.

**Comment by toddhgardner** [comment]
@aaronjensen I'm not sure I understand. Do you load the agent from our CDN and reference it as a webpack external? Can you tell me more about your setup?

**Comment by aaronjensen** [comment]
Yes, exactly. I don't actually do that right now (because I can't afaik), but that's exactly the use case that that supports.  It has the nice effect of allowing someone to include the trackjs package in their package.json for the types but actually load it via the cdn in production, using webpack externals.

Don't get me wrong, I like named exports, I just think that for libraries that could also be available on window exporting as default is less surprising. Alternatively, exporting each function individually so you could `import * as TrackJS from 'trackjs'` is another thing that libs commonly do. It's not a big deal, it'd just fit better with the pattern that other libraries employ (like React) so it'd be less surprising.

**Comment by toddhgardner** [comment]
I've been playing with an example of this in a `create-react-app` setup, and it seems to work fine currently. I have the following setup:

## index.html
```html
<script src="https://cdn.trackjs.com/agent/v3/canary/t.js"></script>
```

## webpack.config.js
```javascript
module.exports = {
  externals: {
    trackjs: 'TrackJS'
  }
}
```

## index.ts
```typescript
import 'trackjs';
TrackJS.install({ token: '123' });
TrackJS.track('hey');
```

This seems to support your use case.

**Comment by toddhgardner** [comment]
In this case, I don't think a named or default export matters, because now we depend on the global and window types just added. There is a draft of this published to npm now, you can see it with

`npm install trackjs@beta`

Will this work for you?

**Comment by aaronjensen** [comment]
Yes, that works. It's a bit odd to use externals combined with an assignment-less import because it means that if I were to remove the external, this would stop working as the import is actually inert.

Personally, I'd probably prefer to see a mixpanel style async import (though with a proper `async` script tag rather than script injection): 

https://help.mixpanel.com/hc/en-us/articles/360000865566-Set-up-Your-Tracking

It has the advantage of declaring the entire api and making it available right away but not blocking the page while loading the script itself. Once the script loads, it'd process any queued errors/identifies/etc.

That combined w/ a default export would allow me the most flexibility. I could use externals if I chose, or I could import the actual lib. If I used externals, `TrackJS` would always be there, even if the lib was blocked. This would mean that the types wouldn't need the `| undefined` on the global declarations.

**Comment by aaronjensen** [comment]
Actually, I think I should backtrack on the "Yes, that works". Unfortunately, if the script doesn't load, webpack externals throws. They really expect the external to be there, so I would need to declare the var myself if the external script fails to load.

Oh, and I realize now the suggestion about the mixpanel method is tricky/maybe a no-go because of all the places you need to hook into to capture errors. There would be a window where those weren't caught unless you actually hooked into those places as part of the snippet which could be a lot of code.

**Comment by toddhgardner** [comment]
Yeah, I agree it's a bit odd, but I think this is a bit of an edge case. Alternatively, but also odd, would be:
### webpack.conf.js
```javascript
module.exports = {
  externals: {
    trackjs: 'window'
  }
}
```

### index.ts
```typescript
import {TrackJS} from 'trackjs';
if (TrackJS) {
  TrackJS.install({ token: '123' });
  TrackJS.track('hey');
}
```

You are correct that this could still cause an issue if the script fails to load. However, you are in a position to do safety checking, like I did with the example. More than this, I think that would best be handled by including the script in your bundle directly, rather than referencing it from our CDN.

I am familiar with the Mixpanel style of loader you referenced, and the issue you pointed out with it. We have not made such a snippet available because delaying the loading of the script will cause a gap in error data during that important initialization phase. 

I think the plan is to move this to our Canary release later today, then push prod sometime over the weekend. Let me know if you'd prefer other changes to the typings.

**Comment by aaronjensen** [comment]
I thought about that, but it was too terrifying to try 😄, but you're right, if that works it could solve the issue w/ the named export.

Is your recommendation to include the script in our bundle? My thinking was:

1. This project isn't updated that often and I'd probably rather have the bug fixes from the cdn version.
2. It can load earlier so it may catch more errors.
3. It can load from a separate domain and so may be more parallelizable. 

The types themselves seem fine, thank you. If anything, I can import them in tsconfig to ensure that `TrackJS` is in scope according to typescript.

**Comment by aaronjensen** [comment]
By the way, just for my own understanding why did you decide to use a named export rather than a default? Is the way to umd in the module world changing?

**Comment by toddhgardner** [comment]
@aaronjensen we do recommend bundling the script with your app, if you have that capability. While you don't get updates to the script, we do fully support all agents, all the way back to 1.0.0. If the agent works for you when you deploy, the likelihood of bugs is low. They usually emerge when we add something new, or a new browser API is released.

Bundling and hosting he script yourself also avoid privacy-blocker extensions. Occasionally, the TrackJS domains get added to a block-domain list, which prevents the script from activating. By hosting locally, some of these issues can be avoided. 

It is also likely faster, as the DNS lookup and SSL handshake for reaching out to a new domain probably take longer than downloading the actual bytes from our CDN in many cases. 

We chose to go with a Named Export of a Default Export for two reasons: first of all, it seemed more common in the other packages. While we saw both styles, newer packages seems to use more naming. Secondly, we intend to add more capability to the module agent for other platforms. Having each of the platforms named will allow users to be more explicit about what they want so the unused components can be left behind when bundling. We're imagining something like this:

```
import { TrackJS, TrackJSServiceWorks, TrackJSReactNative, ... } from 'trackjs';
```

Hope that makes sense!

We're deploying the typescript definition changes now, so I'm closing this issue. Please let me know if there is anything else I can help with!

**Comment by aaronjensen** [comment]
Thanks @toddhgardner, that's helpful. 

I think the main thing that threw me off on the named exports is that the cdn version doesn't use them, but it's web only.

By the way, I'm sure you're thinking about this, but with your plan to bundle multiple platforms in the `trackjs` package you'll want to be careful to ensure that tree shaking is possible and works. I wouldn't want to ship react native and service worker code as part of my bundle. I'd probably prefer to import  from `trackjs/web` just to be certain and not have to rely on webpack to tree-shake.

Cheers!

**Comment by toddhgardner** [comment]
This has been deployed as 3.0.1

Thanks!!
