### ISSUE TITLE
New install instructions would error if the script is blocked

### ISSUE THREAD

**Issue by aaronjensen** [TrackJs/trackjs-package#34]
If the trackjs script is blocked by a tracker blocker, you'd likely get `TrackJS is not defined` when attempting to call `install`. Perhaps this:

```html
<script src="https://cdn.trackjs.com/agent/v3/latest/t.js"></script>
<script>
  TrackJS && TrackJS.install({ 
    token: "..."
    // for more configuration options, see https://docs.trackjs.com
  });
</script>
```

**Comment by toddhgardner** [comment]
Good call on this @aaronjensen, will update the guidance shortly.

**Comment by toddhgardner** [comment]
This is scheduled to go out with our next release.
