### ISSUE TITLE
Internal issue which cause "Attempted to assign to readonly property."

### ISSUE THREAD

**Issue by utlime** [TrackJs/trackjs-package#38]
We started to use `AbortController` with `fetch` and found new issue in trackjs package:
![Screenshot from 2020-05-13 11-47-58](https://user-images.githubusercontent.com/9943271/81772342-cc213d80-950f-11ea-8ef2-edbdcd3cf10a.png)

After some research I found that when `fetch` is aborted it will be rejected with `DOMException`
https://fetch.spec.whatwg.org/#abort-fetch
https://github.com/github/fetch/blob/master/fetch.js#L446

but message in `DOMException` is read only:
https://heycam.github.io/webidl/#idl-DOMException
https://developer.mozilla.org/en-US/docs/Web/API/DOMException/message

Could you please fix that

**Comment by toddhgardner** [comment]
Hey @utlime, Thanks so much for reporting this. Yes, absolutely. I'll have a look at it.

**Comment by toddhgardner** [comment]
I've found the issue and started a release with a fix. I wasn't able to reproduce the thrown "Attempted to assign.." error, but I can confirm that we were attempting to update a readonly property. This seems to silently fail on Chrome, Safari, Firefox. 

Will update when the fixed release is available.

**Comment by utlime** [comment]
from our account
**TOP BROWSERS**
Mobile Safari 13.1
Safari 13.1
Mobile Safari 12.1.2
Mobile Safari 13.0.5
Safari 13.0.5

**Comment by toddhgardner** [comment]
Thanks @utlime!

The fix is live in our canary release now. You can check it by loading the agent from:
https://cdn.trackjs.com/agent/v3/canary/t.js

**Comment by toddhgardner** [comment]
Live in current as 3.7.4
