### ISSUE TITLE
Pass original error name to onError callback

### ISSUE THREAD

**Issue by utlime** [TrackJs/trackjs-package#41]
Background:
We use request abort feature and it cause a lot of network errors which doesn't make sense for us.
In theory it can be done via ignore rules, but it isn't really useful when we have multiple languages and browsers generate different messages.

I found in source code that you pass second argument into onError function which contains name of original error, in short term we will use it, but it would be better if you describe this argument or add name to payload.

I'm going to use this function to avoid abort errors:
```js
(payload: TrackJSErrorPayload, err?: { name: string }) => {
  return !(payload.entry === 'ajax' && err?.name === 'AbortError');
}
```

**Comment by toddhgardner** [comment]
Hi @utlime. Good timing. The Typescript definitions and documentation for the error argument are going live today as part of 3.7.7. 

Your example should work just fine. The originating error (if it exists and is an instance of Error) will be passed through as that second parameter.

We have not previously added `Error.name` to our payload, as we've never found it particularly valuable before, but this is a compelling use case. We'll talk about it more.

I will resolve this once 3.7.7 is out, unless that is unsatisfactory.

**Comment by toddhgardner** [comment]
Documentation has been updated here and 3.7.7 is now available:

https://www.npmjs.com/package/trackjs

https://docs.trackjs.com/browser-agent/sdk-reference/agent-config/#onerror
