### ISSUE TITLE
Documentation for `trackJs.configure` is incorrect

### ISSUE THREAD

**Issue by ninjatronic** [TrackJs/trackjs-package#6]
Many of the [configuration options](http://docs.trackjs.com/JavaScript_Api_Reference/trackJs.configure) are not actually configurable after initialisation.

**Comment by toddhgardner** [comment]
Thanks @ninjatronic, You're right this is a little confusing. We hope to make all the options configurable in a future release, along with your other issue. [https://github.com/TrackJs/trackjs-package/issues/5]
