### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by AdamBrodzinski** [TrackJs/trackjs-package#7]
When I _finally_ got react-native to load the "npm module" with config I ran into a an error that Image is not a function. Since ReactNative doesn't have a browser is there any way to polyfill Image to NoOp and still have the library work? 

This line seems to throw: `(new Image).src=this.trackerFaultEndpoint(a))`

```
c.open(a,b)):c=null;return c},sendTrackerFault:function(a){this.throttle(a)||((new Image).src=this.trackerFaultEndpoint(a))},sendUsage:function(a){(new Image).src=this.usageEndpoint(a)},sendError:function(a,b){var c=this;if(!this.disabled&&!this.throttle(a))try{var d=this.getCORSRequest("POST",this.errorEndpoint(b));d.onreadystatechange=function(){4===d.readyState&&200!==d.status&&(c.disabled=!0)};d._trackJs=k;d.send(h.JSON.stringify(a))}catch(e){throw this.disabled=!0,e;}},throttle:function(a){var b=
```

I love TrackJS but am super bummed I can't use it in my new business :frowning:

**Comment by toddhgardner** [comment]
Hey Adam, thanks for letting us know. We'll look at if there is a way to
make this work for you. Can we have a chat about it? Email me. Todd -at-
TrackJS dotcom

All the best,
Todd.

---

Todd H Gardner
President and CoFounder TrackJS
@toddhgardner

"Building a better web."

**Comment by AdamBrodzinski** [comment]
:+1:  Thanks Todd!

**Comment by mattapperson** [comment]
@toddhgardner any word on this?

**Comment by toddhgardner** [comment]
Hey @mattapperson, unfortunately not. @AdamBrodzinski and I were debugging, but I think other priorities came up. If you'd like to work with me on it, send me an email and we can try out some things. todd@trackjs.com

**Comment by AdamBrodzinski** [comment]
@toddhgardner @mattapperson  Yep, i'm currently swamped. @mattapperson it's partially working and shouldn't take much more fiddling.

**Comment by mikelambert** [comment]
@toddhgardner , closed because it works, or closed because it's not a priority?

**Comment by toddhgardner** [comment]
@mikelambert Closed because @AdamBrodzinski lost interest. Are you interested in picking this up?

**Comment by mikelambert** [comment]
For anyone who stumbles on this issue (like I did!), I've published https://www.npmjs.com/package/react-native-trackjs . It's a bit of a hack at the moment (ie, sets window.document in a way that could potentially break other libraries that try to support both web-and-react-native by checking for using feature detection on window.document). Though it's possible things could get cleaned up with some changes to the TrackJS library down the line...
