### ISSUE TITLE
How can I configure an "application" with this module?

### ISSUE THREAD

**Issue by jviotti** [TrackJs/trackjs-package#8]
According to the documentation, this module only understands the `data-token` attribute, but doesn't allow to set an `application`:

``` js
window._trackJs = {
    token: "................",
    application: "MyApp"
    // other configuration
}
```

**Comment by BrandesEric** [comment]
@jviotti please check out https://github.com/TrackJs/js-integrations for a whole bunch of ways to use this NPM/Bower package with custom configuration.

**Comment by jviotti** [comment]
@BrandesEric Thanks for the information, I got it working successfully.
